# Generated by Django 3.1.7 on 2021-03-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_auto_20210228_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=7000, null=True),
        ),
    ]
